### ISSUE TITLE
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

### ISSUE THREAD

**Issue by Tinky124** [falc0n2/fivem_miami_dump#1]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by Tinky124** [comment]
Zasto editujes moje poruke??

**Comment by falc0n2** [comment]
🤦‍♂️

**Comment by Tinky124** [comment]
@falc0n2 Zasto editujes moje poruke ?????????

**Comment by Tinky124** [comment]
Miami postoji bez dumpa.. ovo je prvi miami sa dumpom..........

**Comment by Tinky124** [comment]
Evo zatvorit cu ovo posto vidim da ne znas :)

**Comment by falc0n2** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by Wtacman** [comment]
eyo dude, can i have ur discord, i have a question for y

**Comment by falc0n2** [comment]
> eyo dude, can i have ur discord, i have a question for y

Yes it's falcon_NWO#6969
